-- Create table for storing user subscriptions (keywords and schedule)
create table if not exists public.tender_subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    keyword text not null,
    schedule_time time not null default '09:00:00',
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for storing aggregated tenders
create table if not exists public.tenders (
    id bigint generated by default as identity primary key,
    title text not null,
    org_name text, -- 機關名稱
    source text default '政府電子採購網',
    url text not null,
    publish_date date,
    keyword_tag text, -- The keyword that matched this tender
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(url) -- Avoid duplicates
);

-- Add RLS policies
alter table public.tender_subscriptions enable row level security;
alter table public.tenders enable row level security;

-- Policies for tender_subscriptions
create policy "Users can view their own subscriptions"
on public.tender_subscriptions for select
using (auth.uid() = user_id);

create policy "Users can insert their own subscriptions"
on public.tender_subscriptions for insert
with check (auth.uid() = user_id);

create policy "Users can update their own subscriptions"
on public.tender_subscriptions for update
using (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
on public.tender_subscriptions for delete
using (auth.uid() = user_id);

-- Policies for tenders
-- All authenticated users can view tenders (or restrict by some logic if needed)
create policy "Authenticated users can view tenders"
on public.tenders for select
to authenticated
using (true);

-- Only service role (n8n) can insert/update tenders
-- (Implicitly, service_role bypasses RLS, so we don't strictly need a policy for it, 
-- but we should ensure anon/authenticated cannot write)
